/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'bg-primary': '#0a0a0a',
      'bg-surface-1': '#121212',
      'bg-surface-2': '#1a1a1a',
      'bg-surface-3': '#242424',
      'text-primary': '#f5f1e8',
      'text-secondary': '#9d9682',
      'accent': '#d4a574',
      'accent-dark': '#a68456',
      'accent-light': '#e8c799',
      'amber': {
        '400': '#fbbf24',
        '500': '#f59e0b',
      },
      'red': {
        '400': '#f87171',
        '500': '#ef4444',
      },
      'white': '#ffffff',
      'black': '#000000',
    },
    fontFamily: {
      'sans': ['Inter', 'Geist', 'system-ui', 'sans-serif'],
      'mono': ['Fira Code', 'SF Mono', 'Monaco', 'monospace'],
    },
    fontSize: {
      'xs': ['12px', '16px'],
      'sm': ['14px', '20px'],
      'base': ['16px', '24px'],
      'lg': ['18px', '28px'],
      'xl': ['20px', '28px'],
      '2xl': ['24px', '32px'],
      '3xl': ['32px', '40px'],
      '4xl': ['48px', '56px'],
      '5xl': ['60px', '72px'],
      '6xl': ['72px', '84px'],
      '7xl': ['96px', '112px'],
    },
    spacing: {
      'xs': '4px',
      'sm': '8px',
      'md': '12px',
      'lg': '16px',
      'xl': '24px',
      '2xl': '32px',
      '3xl': '48px',
      0: '0',
      1: '1px',
      2: '2px',
      4: '4px',
      6: '6px',
      8: '8px',
      12: '12px',
      16: '16px',
      24: '24px',
      32: '32px',
      40: '40px',
      48: '48px',
      56: '56px',
      64: '64px',
    },
    borderRadius: {
      'xs': '2px',
      'sm': '4px',
      'md': '6px',
      'lg': '8px',
      'full': '9999px',
    },
    animation: {
      'fade-in': 'fadeIn 0.3s ease-in',
      'fade-out': 'fadeOut 0.3s ease-out',
      'slide-up': 'slideUp 0.4s ease-out',
      'slide-down': 'slideDown 0.4s ease-out',
      'parallax-shift': 'parallaxShift 0.6s ease-out',
      'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
    },
    keyframes: {
      fadeIn: {
        '0%': { opacity: '0' },
        '100%': { opacity: '1' },
      },
      fadeOut: {
        '0%': { opacity: '1' },
        '100%': { opacity: '0' },
      },
      slideUp: {
        '0%': { opacity: '0', transform: 'translateY(16px)' },
        '100%': { opacity: '1', transform: 'translateY(0)' },
      },
      slideDown: {
        '0%': { opacity: '0', transform: 'translateY(-16px)' },
        '100%': { opacity: '1', transform: 'translateY(0)' },
      },
      parallaxShift: {
        '0%': { opacity: '0', transform: 'translateY(8px) scale(0.98)' },
        '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
      },
      pulse: {
        '0%, 100%': { opacity: '1' },
        '50%': { opacity: '.5' },
      },
    },
  },
  plugins: [],
};

